"""reset_password_table_name_changed

Revision ID: 24d968df563b
Revises: fbc7dbb62e75
Create Date: 2026-01-08 15:13:10.803092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24d968df563b'
down_revision = 'fbc7dbb62e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=False))
        batch_op.drop_column('token_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
